### ISSUE TITLE
Where is my iota ?

### ISSUE THREAD

**Issue by Vikingvp3** [iotaledger/android-wallet-app#105]
Description:
---

I tried to transfer 129497044 iota from my wallet to bitfinex. It make 99 transactions ! My wallet is empty and i did not receive them on bitfinex. Where is my fund ? How can i recover them ? :|

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>327</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>xXx_NoLimits_4.3_OP5_Oxygen_4.5.14</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus5</td></tr>
<tr><td>Device model</td><td>ONEPLUS A5000</td></tr>
<tr><td>Device product name</td><td>OnePlus5</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please contact the bitfinex support team.
