### ISSUE TITLE
Show MIOTA instead iota 

### ISSUE THREAD

**Issue by javitechjkd** [iotaledger/android-wallet-app#106]
Description:
---

I have 6 iota no MIOTA 

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>C432B391</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>EVA-L09C432B391</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWEVA</td></tr>
<tr><td>Device model</td><td>EVA-L09</td></tr>
<tr><td>Device product name</td><td>EVA-L09</td></tr>
<tr><td>Device hardware name</td><td>hi3650</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by javitechjkd** [comment]
Hey, hello all, i am not a developer so i cannot help, but i am testing it. Thanks.

**Comment by pinpong** [comment]
This bug is not confirmed.
