### ISSUE TITLE
App throwing error. Can't connect to remote node.

### ISSUE THREAD

**Issue by woestecabra** [iotaledger/android-wallet-app#108]
Description:
---

Every time I open the app, I receive a message saying there was an error and that it could not connect to remote node. How do I fix this? Balance shows 0. I can't see any node info or neighbors or addresses and cannot generate new addresses. 

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>G935VVRU4BQK2</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G935VVRU4BQK2</td></tr>
<tr><td>Device brand</td><td>Verizon</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2qltevzw</td></tr>
<tr><td>Device model</td><td>SM-G935V</td></tr>
<tr><td>Device product name</td><td>hero2qltevzw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by crcharlie** [comment]
I am having the same problem. 
Network error could not connect remote node.

**Comment by fPolic** [comment]
Change node in setting > node.

**Comment by woestecabra** [comment]
Thank you @fPolic, but do you know which node is trustworthy?  I have tried a few from https://iotasupport.com/gui-lightwallet.shtml and they are not connecting.

**Comment by fPolic** [comment]
http://service.iotasupport.com:14265, worked for me

**Comment by woestecabra** [comment]
Thanks @fPolic. Does it take a while to load account balances and node info after changing nodes? It has been loading for over 10 minutes.

**Comment by fPolic** [comment]
Same here now :/ 
try one of these http://iota.dance/nodes with lowest ping

**Comment by woestecabra** [comment]
Thank you! http://5.9.118.112:14265 worked for me.   :+1:

**Comment by crcharlie** [comment]
node settings has 3 option s Node protocol node IP node port(14265)
Should i change node port?

**Comment by woestecabra** [comment]
Change the IP. Most use port 14265.

**Comment by crcharlie** [comment]
the port is set 14265
node ip:node.iotawallet.info
what should i change it too? i tried http://5.9.118.112:14265  it didn't work.
"node protocol not allowed"

**Comment by woestecabra** [comment]
Protocol should be: http
IP should be: 5.9.118.112
Port should be: 14265
