### ISSUE TITLE
Iota wallet balance

### ISSUE THREAD

**Issue by crcharlie** [iotaledger/android-wallet-app#109]
Description:
---

Wallet balance is zero unable to connect to remote node.

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>G930VVRU4BQK2</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G930VVRU4BQK2</td></tr>
<tr><td>Device brand</td><td>Verizon</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>heroqltevzw</td></tr>
<tr><td>Device model</td><td>SM-G930V</td></tr>
<tr><td>Device product name</td><td>heroqltevzw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by woestecabra** [comment]
I am having the same issue. I entered ticket #108.

**Comment by crcharlie** [comment]
Thank you I will add onto your ticket.

**Comment by pinpong** [comment]
Connect to another remote node and generate few addresses if your balance is not visible.
