### ISSUE TITLE
Endless loading

### ISSUE THREAD

**Issue by eliskcage** [iotaledger/android-wallet-app#112]
Description:
---

Not importing data from the tangle or whatever it is

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>G950FXXU1AQI7</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G950FXXU1AQI7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamlte</td></tr>
<tr><td>Device model</td><td>SM-G950F</td></tr>
<tr><td>Device product name</td><td>dreamltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please connect to another remote node.
