### ISSUE TITLE
Mobile wallet node down?

### ISSUE THREAD

**Issue by Araknai** [iotaledger/android-wallet-app#113]
Description:
---

Can't connect to remote node - http://iota.nodewallet.info:14265

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>3</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NPNS26.118-22-2-3</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>addison</td></tr>
<tr><td>Device model</td><td>XT1635-02</td></tr>
<tr><td>Device product name</td><td>addison</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
The node is already online
