### ISSUE TITLE
My wallet lost

### ISSUE THREAD

**Issue by stereoIII6** [iotaledger/android-wallet-app#114]
Description:
---

LASHVCOJUABYPOJEP9RCSWVZK9NRQMXELFLFJAYWABOUCJMBMLOTVLE9ILKUJWMVZCJILSDZUVTETYLGZ9WS9ZXYGD

It's gone my balance gone 
Where can I see all transactions on my seed with this wallet is it stolen or lost in a bug what happened did I get hacked ???

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>150612185222</td></tr>
<tr><td>Android release version</td><td>5.0.2</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>MEDION_E4005_S12A_207_150612</td></tr>
<tr><td>Device brand</td><td>MEDION</td></tr>
<tr><td>Device manufacturer</td><td>Lenovo</td></tr>
<tr><td>Device name</td><td>E4005</td></tr>
<tr><td>Device model</td><td>MEDION E4005</td></tr>
<tr><td>Device product name</td><td>MEDION</td></tr>
<tr><td>Device hardware name</td><td>mt6582</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
After a snapshot all transaction shall removed. Please generate addresses until your balance is visible.
