### ISSUE TITLE
IOTA WITHDRAW

### ISSUE THREAD

**Issue by ddenerson** [iotaledger/android-wallet-app#120]
Description:
---

Hey Guys, I request a withdraw

 It's been more than 4 
days and the status is still "unconfirmed". Is this normal? Why is it taking so long ? 

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>A300MUBS1BQB3</td></tr>
<tr><td>Android release version</td><td>5.0.2</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX22G.A300MUBS1BQB3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>a3lte</td></tr>
<tr><td>Device model</td><td>SM-A300M</td></tr>
<tr><td>Device product name</td><td>a3lteub</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Click on the transaction and reattach the transaction you want confirmed.
