### ISSUE TITLE
When a wrong node is configured the all crash in login

### ISSUE THREAD

**Issue by diegommarino** [iotaledger/android-wallet-app#123]
Description:
---

When you configure a node with some wrong info and you try to login, after you enter the password and click to login de app close. 

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>WW_Phone-14.0200.1710.340-20171027</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>NMF26F.WW_Phone-14.0200.1710.340-20171027</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>ASUS_X00DD</td></tr>
<tr><td>Device model</td><td>ASUS_X00DDA</td></tr>
<tr><td>Device product name</td><td>WW_Phone</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
I've added hint for the textEdit fields.
