### ISSUE TITLE
Really long transaction time.

### ISSUE THREAD

**Issue by FelipeCarvalho86** [iotaledger/android-wallet-app#124]
Description:
---

Its been more than 19 hours. Should I despair? Have I done something wrong?

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>G532MTVJU1AQK1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29T.G532MTVJU1AQK1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>grandppltedtv</td></tr>
<tr><td>Device model</td><td>SM-G532MT</td></tr>
<tr><td>Device product name</td><td>grandppltedtvvj</td></tr>
<tr><td>Device hardware name</td><td>mt6735</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Did you use local PoW?
