### ISSUE TITLE
Private key compromised

### ISSUE THREAD

**Issue by funkyfranz** [iotaledger/android-wallet-app#129]
Description:
---

I lost all my iota funds after I had a pending transaction where I clicked “re-send“ on the transaction. That function goes without warning and  aparently this compromises the private key/seed.

Device info:
---
<table>
<tr><td>App version</td><td>0.9.1</td></tr>
<tr><td>App version code</td><td>9100</td></tr>
<tr><td>Android build version</td><td>C432B398</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>FRD-L19C432B398</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWFRD</td></tr>
<tr><td>Device model</td><td>FRD-L19</td></tr>
<tr><td>Device product name</td><td>FRD-L19</td></tr>
<tr><td>Device hardware name</td><td>hi3650</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Replay transfer is the same as reattach transaction.

https://github.com/iotaledger/android-wallet-app/blob/master/app/src/main/java/org/iota/wallet/ui/dialog/WalletTransfersItemDialog.java#L106

**Comment by pinpong** [comment]
fixed with 36a1d67
