### ISSUE TITLE
Suggestion: Rebroadcast

### ISSUE THREAD

**Issue by Raganius** [iotaledger/android-wallet-app#13]
Hi, another suggestion.

The "Rebroadcast Transaction" feature.

Whenever there is a new unconfirmed transaction (at each new milestone - untill up to 9 milestones) the tx will be rebroadcast (either automatically - ideal, or even mannually - similarly to the way replay works).

This might be useful, in order to increase confirmation (in this phase of the network). Maybe this function will not be as important in the future when the tangle is more efficient (or, for example, if the "repeater nodes" are successfully implemented).

Thanks!

**Comment by pinpong** [comment]
You can use the replay function if a transaction is not confirmed after several milestone. Click on the transaction and check the options.
