### ISSUE TITLE
Cant see my iota

### ISSUE THREAD

**Issue by dimikolovopoulos** [iotaledger/android-wallet-app#134]
Description:
---

After purchasing some iotas on bitfinex last week i then attempted to transfer them to my wallet. Now 5 days later my wallet either say 'Network error, could not connect to remote node' or 'The connected node ist not fully synced yet'. These error messages occur no matter what i do. 
please help as i would like to recover my holdings.

Device info:
---
<table>
<tr><td>App version</td><td>0.9.2-36a1d67</td></tr>
<tr><td>App version code</td><td>9165</td></tr>
<tr><td>Android build version</td><td>G935FXXU1DQJ3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G935FXXU1DQJ3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>hero2lte</td></tr>
<tr><td>Device model</td><td>SM-G935F</td></tr>
<tr><td>Device product name</td><td>hero2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Wait until the node is synced or choose an other remote node from http://iotasupport.com/lightwallet.shtml

**Comment by dimikolovopoulos** [comment]
It currently is showing me this:

will choosing another remote node still apply?

![iotawall](https://user-images.githubusercontent.com/30293229/33933751-9d6188b6-dfee-11e7-80fc-ce391e9f78c4.png)

**Comment by pinpong** [comment]
Choose a another remote node from the link above.

**Comment by pinpong** [comment]
Go to the settings :p

**Comment by dimikolovopoulos** [comment]
I apprciate you taking the time to help but its not that simple for me.
Can you give me a more precise/detailed walkthrough?
I've tried what you suggested and it completely crashed the app. I had to
uninstall and reinstall just to get it to reopen without closing
automatically.

At this point im genuinely concerned I've lost all my holdings

**Comment by pinpong** [comment]
For example: got to the app settings --> node settings submenu and enter the node configuration below.

Node protocol = `http`
Node IP = `node01.iotatoken.nl`
Node port = `14265`

**Comment by dimikolovopoulos** [comment]
Thank you for replying.

I've tried what youve suggested with several different remote nodes and the
same error is still occuring. :/
'Network Error, could not connect to the remote node'

**Comment by dimikolovopoulos** [comment]
Would it be possible if we could contact each other more directly? If my holdings were to be recovered I'd happy donate some to you in exchange for the assistance. I'm just extremely worried I've lost eveyrthing I've built towards out of no fault of my own.
