### ISSUE TITLE
Iota holdings still not available/visible

### ISSUE THREAD

**Issue by dimikolovopoulos** [iotaledger/android-wallet-app#137]
Previous issue sill applies: 'After purchasing some iotas on bitfinex last week i then attempted to transfer them to my wallet. Now 5 days later my wallet either say 'Network error, could not connect to remote node' or 'The connected node ist not fully synced yet'. These error messages occur no matter what i do.
please help as i would like to recover my holdings.'

This was replied with the following:
Wait until the node is synced or choose an other remote node from http://iotasupport.com/lightwallet.shtml
![iotawall](https://user-images.githubusercontent.com/30293229/33933658-520f97ea-dfee-11e7-8959-5ba98f9156fe.png)

It keeps saying: 'Network error, could not conntect to iota.cool network'

What should i do?

Thanks

**Comment by pinpong** [comment]
iota.cool is for the tangle explorer. Please generate addresses until you balance it back.

**Comment by pinpong** [comment]
Please generate few addresses and change the remote node. iota.cool stops the provided service for the tangle live explorer.
