### ISSUE TITLE
Sincronizzazione 

### ISSUE THREAD

**Issue by sverrellis** [iotaledger/android-wallet-app#138]
Description:
---

Dopo la procedura di recupero delle monimete iota, il wallet non riesce a sincronizzare con il nodo. The connected node is not fully synched yet.

Device info:
---
<table>
<tr><td>App version</td><td>0.9.3-93f24e1</td></tr>
<tr><td>App version code</td><td>9204</td></tr>
<tr><td>Android build version</td><td>4448085</td></tr>
<tr><td>Android release version</td><td>8.1.0</td></tr>
<tr><td>Android SDK version</td><td>27</td></tr>
<tr><td>Android build ID</td><td>OPM1.171019.011</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
It's iota network depended.
