### ISSUE TITLE
Transaction stuck, 3 days and still unconfirmed, what is going on ??

### ISSUE THREAD

**Issue by paboman** [iotaledger/android-wallet-app#139]
Sent some IOTAs to Binance 3 days and 8 hours ago...still pending and not confirmed, how the hell is possible to be slower than BTC blockchain ?
I see this is happening to everyone in the last two weeks! Is there any officiale explanation of the problem from the team ?

https://iotasear.ch/transaction/RI9IGMYIOZBJDOLZDPQBKJKGCAGO9AICYQRLIGGS9KPBPIRUBPOFFVPGNSZBZUDQHAXVHM9RAJJR99999

regards

**Comment by paboman** [comment]
Finally after reattaching the transaction 3 times it has gone thru and arrived to Binance.
big thanks to the telegram support team!

**Comment by mrbianchi** [comment]
try using http://reattach.online

**Comment by 7unkrat** [comment]
The fact that u need to reattach makes it not ready for the mainstream. Reattaching should be an option.
