### ISSUE TITLE
endless network error

### ISSUE THREAD

**Issue by hannesa2** [iotaledger/android-wallet-app#143]
I get in a endless loop network error.

Independent, if it's related to this app or to the network, with this, the complete IOTA story is not use able and obsolete.
Since two weeks I try to send a test amount of IOTA to this wallet, but with network errors I'm not able and even I don't want to transfer some IOTAs.

How to solve it ?
How does a workaround looks like ?
Are there other working nodes ?

**Comment by pinpong** [comment]
You can connect to your own remote node --> https://knarz.github.io/notes/iota-node-do/.

If you want connect to a public remote node please choose one of --> http://iotasupport.com/lightwallet.shtml.
