### ISSUE TITLE
Coin transfer unconfirmed, pending for 20 hours

### ISSUE THREAD

**Issue by xq0404** [iotaledger/android-wallet-app#150]
Description:
---

Wallet app has not yet confirmed my coin transfer since it happened 20 hours ago, even if the desktop gui wallet has already confirmed it.

Device info:
---
<table>
<tr><td>App version</td><td>0.9.109-32ea8fb</td></tr>
<tr><td>App version code</td><td>90109</td></tr>
<tr><td>Android build version</td><td>334(C00)</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>MHA-AL00 8.0.0.334(C00)</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWMHA</td></tr>
<tr><td>Device model</td><td>MHA-AL00</td></tr>
<tr><td>Device product name</td><td>MHA-AL00</td></tr>
<tr><td>Device hardware name</td><td>hi3660</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
The node is not synced yet. Let me restart the node.

**Comment by xq0404** [comment]
thanks a lot. The problem is resolved.
