### ISSUE TITLE
Trying to generate a new address gets Unauthorized

### ISSUE THREAD

**Issue by medisoft** [iotaledger/android-wallet-app#22]
"Unauthorized, the command is not available on this node" is the message I get when trying to generate a new address.

The same nodes can generate addresses for the desktop wallet.

**Comment by pinpong** [comment]
Please update to latest version.

**Comment by brianddk** [comment]
Also happening on v0.9.1 while on node http://iotatoken.nl:14265 @ Dec 6th, 2017, 08:13:00 UTC

**Comment by pinpong** [comment]
@brianddk please enable local PoW within the app settings or use a node that allowes `attachToTangle`.

**Comment by brianddk** [comment]
@pinpong Right On!! That did the trick... though I did just get lucky on the `attachToTangle` privilege.  I didn't see it in the node properties after I attached.  Did I miss it, or is there a node browser / JSON api that might show client privileges of the public-light-nodes?
