### ISSUE TITLE
Wrong conversion

### ISSUE THREAD

**Issue by gogibogi4** [iotaledger/android-wallet-app#25]
Description:
---

In my wallet 800 Gi is displayed as 300€

Device info:
---
<table>
<tr><td>App version</td><td>0.6</td></tr>
<tr><td>App version code</td><td>6000</td></tr>
<tr><td>Android build version</td><td>3938523</td></tr>
<tr><td>Android release version</td><td>7.1.2</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>N2G47W</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>bullhead</td></tr>
<tr><td>Device model</td><td>Nexus 5X</td></tr>
<tr><td>Device product name</td><td>bullhead</td></tr>
<tr><td>Device hardware name</td><td>bullhead</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by adrianziser** [comment]
Fixed with 2f9897f
Latest release available via Google Play
