### ISSUE TITLE
Seed font makes 0 (zero) indistinguishable from O (Oh)

### ISSUE THREAD

**Issue by arancauchi** [iotaledger/android-wallet-app#28]
A small ux issues where seeds are ambiguously displaying zero and oh as nearly the same character.
I am aware that only the number 9 can be present in a seed, but this is not immediately apparent to general users. Suggest changing seed font to Roboto Mono, or similar.

**Comment by SoaringMoon** [comment]
The seed cannot contain zero anyhow. That would be invalid.

**Comment by pinpong** [comment]
That issue is fixed already by another patch.
