### ISSUE TITLE
(Optionally) do PoW on the phone

### ISSUE THREAD

**Issue by toonsevrin** [iotaledger/android-wallet-app#30]
I was looking at the source of the android wallet and it seems like it does sendTransfer for a new transfer, which requires a full node that exposes attachToTangle (these are not common). Can we revive https://github.com/iotaledger/iota.curl.java?

**Comment by pinpong** [comment]
Closed by [55a6f76](https://github.com/iotaledger/android-wallet-app/commit/55a6f762fd919d282efaab5ba8cd74f603deb1fc).
