### ISSUE TITLE
Confirmed

### ISSUE THREAD

**Issue by brucewagner** [iotaledger/android-wallet-app#31]
Description:
---

There is no indication of which transactions are mine, or of when it will show as Confirmed.

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>G955FXXU1AQF7</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G955FXXU1AQF7</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2lte</td></tr>
<tr><td>Device model</td><td>SM-G955F</td></tr>
<tr><td>Device product name</td><td>dream2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
The UI has already been improved..
