### ISSUE TITLE
Gas44

### ISSUE THREAD

**Issue by Gas44** [iotaledger/android-wallet-app#34]
Description:
---

NSAWHDKFSGVKLXENRTGPLXAFHCAGIZMSXFRKXBQUICXXIDJNUVNXLCKXIO9TXATZXPMSRNNRESSKTKAOE

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>I9500XXUHPK1</td></tr>
<tr><td>Android release version</td><td>5.0.1</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX22C.I9500XXUHPK1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>ja3g</td></tr>
<tr><td>Device model</td><td>GT-I9500</td></tr>
<tr><td>Device product name</td><td>ja3gxx</td></tr>
<tr><td>Device hardware name</td><td>universal5410</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
No description.
