### ISSUE TITLE
Issue with creating new address and reporting issues

### ISSUE THREAD

**Issue by brandonhuddle** [iotaledger/android-wallet-app#37]
Description:
---

The plus button in the addresses tab does nothing for me and when reporting an issue with my email I get an invalid token error message. A few minutes after clicking the plus button I get a notification saying an address was created but the tab is still empty.

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>14</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NPL25.86-15</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>griffin</td></tr>
<tr><td>Device model</td><td>XT1650</td></tr>
<tr><td>Device product name</td><td>griffin</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Should fixed with v0.6.3.
