### ISSUE TITLE
Invalid recipient address.

### ISSUE THREAD

**Issue by michael203ct** [iotaledger/android-wallet-app#38]
Description:
---

I keep getting the above message when trying to send miota. Also, no address shows after scams qr code. Please help! Want to send total balance to the following address : XYVGNLFEZY9PDKAGFLLBVMRRUYTXRABEIBQJCDSZVC9COUQNQCFOTKNAJFPYFNOSLJFM99YL

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>G950USQU1AQGA</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G950USQU1AQGA</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamqltesq</td></tr>
<tr><td>Device model</td><td>SM-G950U</td></tr>
<tr><td>Device product name</td><td>dreamqltesq</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
You scan a qr code from bitfinex?

**Comment by michael203ct** [comment]
Yes. I was able to finally put the address in manually. The problem now is
that I have a pending transaction from August 13, 2017 for 524 miota . Why
is it not transferring?

**Comment by pinpong** [comment]
Please use the replay transaction option. Sometimes a trx is not seen.

**Comment by michael203ct** [comment]
Replay bundle, or just make a new transaction..? I don't see a 'replay
transaction' option.

**Comment by pinpong** [comment]
replay bundle

**Comment by michael203ct** [comment]
Ok, done. I don't think it worked. It's been 5+ minutes now.

**Comment by michael203ct** [comment]
What's going to happen to my funds? Transaction still didn't go through.
Also, now I can't even log into account. I get a message that reads,
'network error, could not connect to the remote node'.
