### ISSUE TITLE
ReadMe does not describe what the app is meant to do

### ISSUE THREAD

**Issue by akinmail** [iotaledger/android-wallet-app#4]
This project has not been implemented, i am interested in contributing but i have no idea what the requirements for this app are. Shouldn't the readme file explain the direction you want this project to take? Do you accept pull request from developers that are not part of your core team?

**Comment by pinpong** [comment]
Its a native android wallet application.

**Comment by adrianziser** [comment]
The sourcecode will be available soon and everybody is welcome to contribute. For sure do we accept pull requests.
