### ISSUE TITLE
Bitfinex transfer not received

### ISSUE THREAD

**Issue by stekliPes** [iotaledger/android-wallet-app#42]
I have sent 100 Mi from Bitfinex to IOTA Wallet a month ago. Bitfinex shows transaction as completed. Up until a few days ago the wallet was showing the transaction as pending, and now it is not showing it at all.
My IOTA wallet balance iz 0.

**Comment by stekliPes** [comment]
Also ,I am unable to submit the bug report from the mobile application -> it says "invalid access token, please contact the app developer"

**Comment by pinpong** [comment]
It's not app related.

**Comment by stekliPes** [comment]
How can it not be app related if addresses and transactions disappeared
from my app?

On Thu, Aug 17, 2017 at 12:33 PM, Oliver Nitzschke <notifications@github.com

**Comment by pinpong** [comment]
Did you already updated to v0.6.3?

**Comment by stekliPes** [comment]
Yes, I am updated to 0.6.3.

On Thu, Aug 17, 2017 at 12:43 PM, Oliver Nitzschke <notifications@github.com

**Comment by stekliPes** [comment]
Does updating to a new version cause transactions to become lost?

**Comment by pinpong** [comment]
You have to follow the steps in the blog post:

https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

**Comment by stekliPes** [comment]
I have followed this procedure, i generated over 1000 addresses already, my
transaction nor mi IOTAs did not show up.

**Comment by stekliPes** [comment]
The procedure described above did not restore my IOTAs nor did it find the
transaction that was never completed.

**Comment by stekliPes** [comment]
I have tried the above procedure numerous times. It did not restore the
missing transaction nor mi IOTAs. Please assist me in recovering my money
that disappeared from the wallet.

**Comment by stekliPes** [comment]
I have updated to the latest app version, I have followed the transition
procedure, I have tried to generate addresses in order to recover my funds
but they are gone. Please assist.

**Comment by pinpong** [comment]
Was the transition successfully and the transaction confirmed?

**Comment by stekliPes** [comment]
The transaction was successful at bitfinex side, and was pending in the wallet. Then it disappeared from the wallet. After that I tried to restore it by regenerating addresses and following the above procedure, but it did not help.

-----Original Message-----

**Comment by stekliPes** [comment]
Did anyone, determine how and why was the transaction lost? How can I
recover my money? I have all the newest versions of the software and the
procedure provided above did not help, nor did regenerating addresses help.
