### ISSUE TITLE
Lost my Iota?

### ISSUE THREAD

**Issue by patrickvanderweg** [iotaledger/android-wallet-app#43]
Description:
---

Hello, i had 408 Iota in my wallet on my phone. But today i looked and the ammount was 0.
Where are my 408 Iota????

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>G930FXXU1DQEI</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G930FXXU1DQEI</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>herolte</td></tr>
<tr><td>Device model</td><td>SM-G930F</td></tr>
<tr><td>Device product name</td><td>heroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8890</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by dthorpe** [comment]
https://github.com/iotaledger/android-wallet-app/issues/44#issuecomment-321873427

**Comment by dthorpe** [comment]
If I understand the IOTA network situation correctly, your IOTA is still out there and bound to your private keys, its just that the wallet can't talk to the updated network protocol until the wallet code itself is updated.  Whatever you do, DONT delete your wallet or private keys!

**Comment by patrickvanderweg** [comment]
I've got them back!
Where can i find my private key?

Op 11 aug. 2017 19:37 schreef "Danny Thorpe" <notifications@github.com>:

**Comment by patrickvanderweg** [comment]
Hello, i have the same problem again.
Again my 408 iota is gone when i login my wallet.
How is that possible???
I must trust this wallet/iota.

Thanx 4 your answer

Op 17 aug. 2017 12:29 schreef "Oliver Nitzschke" <notifications@github.com>:
