### ISSUE TITLE
Can't see my funds

### ISSUE THREAD

**Issue by louismza** [iotaledger/android-wallet-app#44]
Description:
---

Hey, my funds have disappeared. I am definitely using the correct seed. Can you please help? 

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>90</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A3010_28_170610</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus3T</td></tr>
<tr><td>Device model</td><td>ONEPLUS A3010</td></tr>
<tr><td>Device product name</td><td>OnePlus3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by dthorpe** [comment]
Probably related to the network change that happened earlier this week - changing the hash function from curl to SHA3, if I recall.  All wallets must deploy a code update to be able to talk to the "new" network.  Funds and private keys should be secure, we just can't see our balances until our wallet is updated to speak the new lingo of the new network.

**Comment by hoops74** [comment]
Hi, i have the same problem. I bought iota put them in my android app wallet , all was fine, logged in the other day (7th Jan 2018) to find nothing
