### ISSUE TITLE
Generierte Empfangsadressen stehen auf Pending 

### ISSUE THREAD

**Issue by shagodu72** [iotaledger/android-wallet-app#45]
Description:
---

Ich habe drei Adressen für den Empfang generiert. Diese stehen seit geraumer Zeit auf Pending. Ich habe ohne Erfolg ein Rebroadcasting durchgeführt. Wenn ich IOTA von Bitfinex auf eine der Adressen teansferieren möchte meldet Bitfinex "invalid adress". 

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>1716716574eec</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90U</td></tr>
<tr><td>Device brand</td><td>lge</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>pplus</td></tr>
<tr><td>Device model</td><td>LG-H960</td></tr>
<tr><td>Device product name</td><td>pplus_global_com</td></tr>
<tr><td>Device hardware name</td><td>pplus</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Adressen müssen nicht bestätigt werden. Du kannst diese trotzdem nutzen.
