### ISSUE TITLE
Überweisungen gehen nicht durch

### ISSUE THREAD

**Issue by mstreicher** [iotaledger/android-wallet-app#47]
Description:
---

Habe 230 Mi an eine andere adresse geschickt und die ist seit 19 Stunden auf ausstehend. Bitte um sofortige behebung!

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>G925FXXS5EQG1</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G925FXXS5EQG1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zerolte</td></tr>
<tr><td>Device model</td><td>SM-G925F</td></tr>
<tr><td>Device product name</td><td>zeroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Update to v0.6.3 and replay the transaction.
