### ISSUE TITLE
Missing iota

### ISSUE THREAD

**Issue by andrewmegaris** [iotaledger/android-wallet-app#48]
Description:
---

Testing your wallet, lost 10m iota sometime last week

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>5</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MCG24.251-5-5</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>quark</td></tr>
<tr><td>Device model</td><td>XT1254</td></tr>
<tr><td>Device product name</td><td>quark_verizon</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Please update to v0.6.3.

**Comment by andrewmegaris** [comment]
I have updated my wallet and it still shows as empty.  Now I get an error "Network error, could not connect to the remote node"  I have tried this using two different WiFi(wep2 and wpa) and Cellular networks.
