### ISSUE TITLE
cannot see balance

### ISSUE THREAD

**Issue by arkoak** [iotaledger/android-wallet-app#49]
Description:
---

I login using the same seed on windows and can see balance but when I copy the seed to mobile and login it seems to be a different account with zero balance and no transactions

Device info:
---
<table>
<tr><td>App version</td><td>0.6.1</td></tr>
<tr><td>App version code</td><td>6100</td></tr>
<tr><td>Android build version</td><td>G930AUCS2APH1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.G930AUCS2APH1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>heroqlteatt</td></tr>
<tr><td>Device model</td><td>SAMSUNG-SM-G930A</td></tr>
<tr><td>Device product name</td><td>heroqlteuc</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please update to v0.6.3.
