### ISSUE TITLE
Replay

### ISSUE THREAD

**Issue by Raganius** [iotaledger/android-wallet-app#5]
Hi,
The isse I'd like to report is: when you tap on a pending transaction, and do a replay, there is no indication that the replay is being done, so, for the user, it seem like replay is not working.

But when I check on iota.cool, there are many replays (attempts) of my transaction (as I have tapped replay many times, because of having no indication that the previous replays have been made).

Thanks for the great app.

**Comment by adrianziser** [comment]
Hey, thanks for your feedback. A notification for replayTransfer will be included in the next beta release. Btw, no need to check on iota.cool, we cooperated with alfred (the creator of iota.cool) and the last 500 transactions are now also displayed inside the app (tangle explorer).

**Comment by pinpong** [comment]
included in v2.0 BETA
