### ISSUE TITLE
'Not availavle - android app

### ISSUE THREAD

**Issue by TheJaseku** [iotaledger/android-wallet-app#50]
Description:
---

I used the same seed as with my pc, but the balance does not show up on the app

Device info:
---
<table>
<tr><td>App version</td><td>0.6.3</td></tr>
<tr><td>App version code</td><td>6300</td></tr>
<tr><td>Android build version</td><td>3437181</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>M4B30Z</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>hammerhead</td></tr>
<tr><td>Device model</td><td>Nexus 5</td></tr>
<tr><td>Device product name</td><td>hammerhead</td></tr>
<tr><td>Device hardware name</td><td>hammerhead</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by mkncold** [comment]
Is it showing the correct balance on PC? Have you gone through the transition steps?
https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

**Comment by pinpong** [comment]
Is your problem solved?

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
