### ISSUE TITLE
No funds when connected to new node

### ISSUE THREAD

**Issue by gogibogi4** [iotaledger/android-wallet-app#51]
I connected to another nodes and i would like to make my funds appear

**Comment by gogibogi4** [comment]
Also i am using the 0.6.3 wallet and i have made the transaction to the wallet 23.6.2017

**Comment by gogibogi4** [comment]
I reversed to the old node and still have no funds

**Comment by pinpong** [comment]
Please visit https://iotasupport.com and read the FAQ.
