### ISSUE TITLE
App showing version 0.6.5 but bug report showing app version 0.6.1

### ISSUE THREAD

**Issue by arkoak** [iotaledger/android-wallet-app#52]
Downloaded the latest IOTA wallet app. the version shows 0.6.5 on playstore.
IN app, it also shows version 0.6.5 in the about page.
But when I open changelog it only shows changes upto 0.6.1
when I report a bug it also shows up as version 0.6.1 (and that version of course is not compatible with current wallet structure) 
Cannot operate my upgraded wallet on this version currently available on playstore

**Comment by pinpong** [comment]
That's should already fixed.
