### ISSUE TITLE
New Wallet Wont Accept Seed.

### ISSUE THREAD

**Issue by Neopatriarch** [iotaledger/android-wallet-app#54]
This question was originally published at https://github.com/iotaledger/wallet/issues/233

It was suggested by @wonkytonky that I ask here. I do hope you can help.

I have an android wallet, that carries my balance.

I have successfully downloaded the windows wallet. It requests the seed to transfer the balance.

However, it will not accept either the original string I entered nor the seed presented under >settings>>password>show seed in the Android app. The string it shows is similar in every way to the original accept all the words are upper case and all spaces have "9"s.

What to do? Please help.

**Comment by SoaringMoon** [comment]
You would write down the see shown. The wallet replaces spaces with 9's and pads the end with 9's as well. The seed listed in your settings is the correct seed.

**Comment by Neopatriarch** [comment]
Thanks for trying SoaringMoon. Unfortunately, it didn't work. I tried copy and pasting. I tried typing myself. The original, as I wrote it down, was lowercase. the system seed is like the caps locks on.

Is there anyway just to send the iota to an altogether new wallet?

**Comment by Neopatriarch** [comment]
Yeah no matter what I do I throw an "invalid seed" error.

**Comment by wonkytonky** [comment]
so i went trough the code of the windows wallet  
it trows the error   only if its somthing else then capital letters and not 9 

so  something is still wrong.. like a little space  maybe somewhere, maybe at the end?..
somewhere there's a bad  character in your seed that you type in or copypaste

**Comment by Neopatriarch** [comment]
Thanks so much for taking the time to help me. 

Okay, I used the Capitalized string, and counted out spaces to 81, also without the extra spaces. Still got "Invalid Seed" error.

Perhaps the text editor, Google Docs is adding something.... I will try to strip out any such formatting. Mayhaps if I save it as a txt file and pull from there. I will try. report back in a minute.

**Comment by Neopatriarch** [comment]
How disappointing. I downloaded the doc as a txt file and opened in notepad. Two attempts with and without spaces to make 81digits.

**Comment by wonkytonky** [comment]
did you replace spaces with 9?

**Comment by Neopatriarch** [comment]
No, then yes. It's seems to be working!!!

**Comment by Neopatriarch** [comment]
@wonkytonky you're my new best friend. Thanks so much.

Okay its asking for a new seed. Should I just make up another string?

**Comment by wonkytonky** [comment]
yes and this time  make 81 long   CApital letters  and only number 9

**Comment by Neopatriarch** [comment]
Okay, everything seems to be good. I see my balance in history. It's been working for 17 minutes. Should I reattach or retransmit?

**Comment by wonkytonky** [comment]
is your "transmission" transactions still pending? ..   wait for 30 if not confirmed.. reattach

**Comment by Neopatriarch** [comment]
I did have to reattach. It worked my balance is now correct.

Thank you Thank you Thank you
