### ISSUE TITLE
Second problem

### ISSUE THREAD

**Issue by andrewmegaris** [iotaledger/android-wallet-app#56]
Description:
---

I updated my version of the wallet as recommended from my last 'issue'. Concerning the iota that disappeared. Now that I have updated I get 'network error: could not connect to remote node'. I have tried on cellular, and wif(wpa, and wep2) networks.

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>5</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MCG24.251-5-5</td></tr>
<tr><td>Device brand</td><td>motorola</td></tr>
<tr><td>Device manufacturer</td><td>motorola</td></tr>
<tr><td>Device name</td><td>quark</td></tr>
<tr><td>Device model</td><td>XT1254</td></tr>
<tr><td>Device product name</td><td>quark_verizon</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
You have to be sure that the remote node is reachable.
