### ISSUE TITLE
Pending transfer disappeared from app, cannot reattach

### ISSUE THREAD

**Issue by stekliPes** [iotaledger/android-wallet-app#58]
I have sent 100 Mi from Bitfinex to IOTA Wallet a month ago. Bitfinex shows transaction as completed. Up until a few days ago the wallet was showing the transaction as pending, and now it is not showing it at all.

I have updated to the latest app version.
I have tried to follow the instructions here: https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412 (numerous times), to no avail. 

My IOTA wallet balance iz 0, and the transaction is nowhere to be foundč

**Comment by pinpong** [comment]
You problem is solved?

**Comment by stekliPes** [comment]
Yes, it was solved, the lost IOTAs are back in my account. Thank you for
help!
