### ISSUE TITLE
The problem with my mobile wallet.

### ISSUE THREAD

**Issue by melxisedek** [iotaledger/android-wallet-app#59]
Description:
---

Hello my mobile wallet does not display the amount of my yot, which I transferred from the bitfinex exchange.In the desktop version of the wallet the translation is displayed in 1600 iot

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>N920TUVU4EQG3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.N920TUVU4EQG3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>nobleltetmo</td></tr>
<tr><td>Device model</td><td>SM-N920T</td></tr>
<tr><td>Device product name</td><td>nobleltetmo</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please visit the https://otasupport.com and read the FAQ.
