### ISSUE TITLE
Suggestion: separate secure from insecure addresses to receive funds on

### ISSUE THREAD

**Issue by anuzis** [iotaledger/android-wallet-app#61]
**Problem**
From my understanding, it's safe to receive repeated transactions to the same address, but unsafe to send multiple transactions from the same address. The current Android IOTA UI shows all 'Addresses' equally. As a newer user who has done a few transactions in and out, it's confusing to keep track of which addresses are safe to send new transactions to, and which have already been used to send transactions.

I understand the value in keeping a list of all prior addresses used since users may want to verify past transaction history associated with old addresses. However, that use case is completely different from finding an address for accepting new secure transactions.

**Suggested Solution**
The UI should differentiate addresses safe for new deposits from addresses saved for historic reasons.

_Quick and Dirty Fixes (Sufficient):_ 

- Use two different icons to the left of each address: one that keeps the existing bank image (for secure addresses), and one that brings attention to the fact the address is of a different type. It could be a "!" (exclamation mark) which conveys a "warning" feel. Perhaps a better icon with less emphasis on the security weakness could be a clock that conveys a "historical" feel. Users won't know what each icon means, but should be able to click the icon for an explanation.  e.g. Bank icon: "This address has never sent funds and is secure to receive new transactions."  e.g. Clock icon: "This address has sent transactions in the past and should not be used to receive new transactions. It's saved as a reference for past transactions."
- Remove the "Receive to this address" option that displays for historical (insecure) addresses.
- Consider displaying a warning for the "Copy" option for historical (insecure) addresses that they should only be copied to look up historical transactions.

_Longer Term Fixes (better user experience):_ 
- Rename "Addresses" tab to "Receive", and have it only display addresses that can securely receive new transactions.
- Update "Transactions" tab to show "Sender Address" and "Receiving Address" to disambiguate the current "Address" and make the user's historic receiving address available if they need to find it.
- Remove the "Receive to this address" option for insecure addresses.

I'm sure more elegant solutions are available, just trying to suggest some straight forward options that should help prevent users from making insecure transactions.

**Comment by pinpong** [comment]
Thanks for the suggestion.

**Comment by pinpong** [comment]
![address_tab](https://user-images.githubusercontent.com/1012532/30937987-d32c16f2-a3d8-11e7-8beb-1e8398a59363.jpg)

@anuzis what are you thinking?
