### ISSUE TITLE
Balance in zero 

### ISSUE THREAD

**Issue by h2oven** [iotaledger/android-wallet-app#62]
Description:
---

I can't see my iota coins in the wallet, can you help me to solve it, please. 

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>87</td></tr>
<tr><td>Android release version</td><td>7.1.1</td></tr>
<tr><td>Android SDK version</td><td>25</td></tr>
<tr><td>Android build ID</td><td>ONEPLUS A3003_16_170821</td></tr>
<tr><td>Device brand</td><td>OnePlus</td></tr>
<tr><td>Device manufacturer</td><td>OnePlus</td></tr>
<tr><td>Device name</td><td>OnePlus3</td></tr>
<tr><td>Device model</td><td>ONEPLUS A3003</td></tr>
<tr><td>Device product name</td><td>OnePlus3</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please visit https://iotasupport.com or use the official slack to get help.
