### ISSUE TITLE
Address keep showing ' not yet implemented'

### ISSUE THREAD

**Issue by wowlwow** [iotaledger/android-wallet-app#63]
Description:
---

IOTA arrival stay in pending foe days now. Anyway to change it to confirm state?

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>1619418088183</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MRA58K</td></tr>
<tr><td>Device brand</td><td>lge</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>p1</td></tr>
<tr><td>Device model</td><td>LG-H812</td></tr>
<tr><td>Device product name</td><td>p1_rgs_ca</td></tr>
<tr><td>Device hardware name</td><td>p1</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please use the replay bundle function.
