### ISSUE TITLE
No data showed

### ISSUE THREAD

**Issue by sdellava** [iotaledger/android-wallet-app#65]
Description:
---

After login app remain in the initial data grabbing state

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>WW_Z00A-WW_2.20.40.198_20160930_8756_user_rel-user-20160930</td></tr>
<tr><td>Android release version</td><td>5.0</td></tr>
<tr><td>Android SDK version</td><td>21</td></tr>
<tr><td>Android build ID</td><td>LRX21V.WW-ASUS_Z00A-2.20.40.198_20160930_8756_user</td></tr>
<tr><td>Device brand</td><td>asus</td></tr>
<tr><td>Device manufacturer</td><td>asus</td></tr>
<tr><td>Device name</td><td>Z00A</td></tr>
<tr><td>Device model</td><td>ASUS_Z00AD</td></tr>
<tr><td>Device product name</td><td>WW_Z00A</td></tr>
<tr><td>Device hardware name</td><td>mofd_v1</td></tr>
<tr><td>ABIs</td><td>[x86, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[x86, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Is your problem fixed with the latest version?

**Comment by pinpong** [comment]
Please check if you enter the right seed or check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
