### ISSUE TITLE
Can not access my Iota coins 

### ISSUE THREAD

**Issue by Ray2022003** [iotaledger/android-wallet-app#66]
Description:
---

My app can't connect to the Iota chain. So I can't access my coins frequently. What is wrong with the app? 

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>V8.2.4.0.MBEMIDL</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M</td></tr>
<tr><td>Device brand</td><td>Xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>markw</td></tr>
<tr><td>Device model</td><td>Redmi 4</td></tr>
<tr><td>Device product name</td><td>markw</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please update to the latest version.
