### ISSUE TITLE
8Mi verschwunden

### ISSUE THREAD

**Issue by hockeyservices** [iotaledger/android-wallet-app#67]
Description:
---

Ich hatte auf der Android App 8Mi gelagert. Testweise. Nun scheint 0 auf. Auf Anraten habe ich schon mehr als 20 Adressen generiert. Keine Änderung. 

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>C432B381</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>VNS-L21C432B381</td></tr>
<tr><td>Device brand</td><td>HUAWEI</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWVNS-H</td></tr>
<tr><td>Device model</td><td>HUAWEI VNS-L21</td></tr>
<tr><td>Device product name</td><td>VNS-L21</td></tr>
<tr><td>Device hardware name</td><td>hi6250</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Did you already followed the [instructions](https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412)?

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
