### ISSUE TITLE
I lost 14 characters of my first seed and now I lost all my IOTAS

### ISSUE THREAD

**Issue by vllgsscr** [iotaledger/android-wallet-app#68]
Description:
---

I copy and paste the seed but the hightlight left 14 characters out and now Im missing them to login into my main wallet

Device info:
---
<table>
<tr><td>App version</td><td>0.6.5</td></tr>
<tr><td>App version code</td><td>6500</td></tr>
<tr><td>Android build version</td><td>J700T1UVS3AQF1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.J700T1UVS3AQF1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j7eltemtr</td></tr>
<tr><td>Device model</td><td>SM-J700T1</td></tr>
<tr><td>Device product name</td><td>j7eltemtr</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7580</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Sorry for your loss but thats not really an app issue. The text edit view is already improved.
