### ISSUE TITLE
Mobile App Closes

### ISSUE THREAD

**Issue by McAleer2018** [iotaledger/android-wallet-app#69]
Description:
---

Mobile app jist crashes as you enter the seed. Using latest app available from official IOTA app store for ANDROID

Device info:
---
<table>
<tr><td>App version</td><td>0.7</td></tr>
<tr><td>App version code</td><td>7000</td></tr>
<tr><td>Android build version</td><td>16054235401ba</td></tr>
<tr><td>Android release version</td><td>6.0</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MRA58K</td></tr>
<tr><td>Device brand</td><td>lge</td></tr>
<tr><td>Device manufacturer</td><td>LGE</td></tr>
<tr><td>Device name</td><td>g4stylusn</td></tr>
<tr><td>Device model</td><td>LG-H635</td></tr>
<tr><td>Device product name</td><td>g4stylusn_global_com</td></tr>
<tr><td>Device hardware name</td><td>g4stylusn</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
Is this happening only once?

**Comment by McAleer2018** [comment]
It is crashing constantly. Waiting on the IOTA Team to perhaps release an update for the app on the Android store, I would prefer for this not to be closed

**Comment by pinpong** [comment]
Please wipe the app data and try it again.

**Comment by McAleer2018** [comment]
Hi there seems to have corrected, I wiped the app data, app failed once, uninstalled, reinstalled, ran it and it works fine so far
