### ISSUE TITLE
Wheres my IOTA?

### ISSUE THREAD

**Issue by DrBalls** [iotaledger/android-wallet-app#72]
Description:
---

All my IOTA disappeared

Device info:
---
<table>
<tr><td>App version</td><td>0.7</td></tr>
<tr><td>App version code</td><td>7000</td></tr>
<tr><td>Android build version</td><td>4286350</td></tr>
<tr><td>Android release version</td><td>8.0.0</td></tr>
<tr><td>Android SDK version</td><td>26</td></tr>
<tr><td>Android build ID</td><td>OPR3.170623.007</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Google</td></tr>
<tr><td>Device name</td><td>marlin</td></tr>
<tr><td>Device model</td><td>Pixel XL</td></tr>
<tr><td>Device product name</td><td>marlin</td></tr>
<tr><td>Device hardware name</td><td>marlin</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by GoneUp** [comment]
Did you do the transition? https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

**Comment by GoneUp** [comment]
Did you do the transition? https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

**Comment by pinpong** [comment]
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
