### ISSUE TITLE
Showing zero balance

### ISSUE THREAD

**Issue by ch3ckmat3** [iotaledger/android-wallet-app#73]
Description:
---

The app is showing zero balance after last update. Any advice? 

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>G920AUCS5DPJ1</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29K.G920AUCS5DPJ1</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zeroflteatt</td></tr>
<tr><td>Device model</td><td>SAMSUNG-SM-G920A</td></tr>
<tr><td>Device product name</td><td>zeroflteuc</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please generate addresses.

**Comment by ch3ckmat3** [comment]
How? can you please explain

**Comment by GoneUp** [comment]
Did you do the transition? https://blog.iota.org/new-gui-transition-phase-explained-b536ed80f412

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
