### ISSUE TITLE
Dejan milivojevic

### ISSUE THREAD

**Issue by dejandex** [iotaledger/android-wallet-app#74]
Description:
---

My iota stolen from my walet 94 iota send to some adress please help to recovere my iota 

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>G955FXXU1AQH3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G955FXXU1AQH3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2lte</td></tr>
<tr><td>Device model</td><td>SM-G955F</td></tr>
<tr><td>Device product name</td><td>dream2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by GoneUp** [comment]
What you want to tell us? Was your seed stolen? 
Unfortunately there is no way to reverse transaction once they are done.

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
