### ISSUE TITLE
Missing Transactions and Blanace

### ISSUE THREAD

**Issue by BFTremans72** [iotaledger/android-wallet-app#75]
Hi, 
My IOTA Balance is completely missing from my local IOTA wallet?
Moreover, it displays 0 transactions, where it should be at least one, when I moved my IOTA tokens from an exchange into local wallet. There may be sync issue but I need directions on how to re-sync it
Please advice!

Thank you!

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
