### ISSUE TITLE
Transaction pending.

### ISSUE THREAD

**Issue by KAMALKUMARBORO** [iotaledger/android-wallet-app#76]
Description:
---

I tried to send some IOTA using this android app to an address generated from another seed in the same app. i.e. same app, two different seeds , trying to send IOTA from the address of first seed to the address of second seed. The request is pending for the last three days 

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>V8.5.8.0.NCFMIED</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>AL1512-mido-build-20170915223957</td></tr>
<tr><td>Device brand</td><td>xiaomi</td></tr>
<tr><td>Device manufacturer</td><td>Xiaomi</td></tr>
<tr><td>Device name</td><td>mido</td></tr>
<tr><td>Device model</td><td>Redmi Note 4</td></tr>
<tr><td>Device product name</td><td>mido</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
Please try to replay the bundle.
