### ISSUE TITLE
Suggestion: The Adresses Tab

### ISSUE THREAD

**Issue by Raganius** [iotaledger/android-wallet-app#8]
The addresses tab seems to be a little confusing, because it shows not only the addresses derived from the current seed on the user's wallet, but also shows address from other wallets (related to past transactions).

It could be a good solution if the Address tab shows only the last generated address from the current seed, or at least, if it only shows addresses devived from the current seed.

By showing addresses that do not belong to the user's own wallet, there is the possibility that the user may use this "wrong address" instead of on of his own addresses.

Thank you.

**Comment by pinpong** [comment]
The address tab is fixed.
