### ISSUE TITLE
Balance 0

### ISSUE THREAD

**Issue by gregipfister** [iotaledger/android-wallet-app#80]
Description:
---

Hi Iota Team

Habe heute 2 Std. Probiert meinen Kontostand von 31.18Miotas anzeigen zu lassen. Folgendes wurde bereits erfolglos durchgeführt.
- Am PC Wallet Version 2.4  versuch der transition mit der erstellung von 5000 adressen.. fehlgeschlagen > Balance 0
- Am PC Wallet Version 2.5.1 probiert neue adressen zu generieren unf die an den tangle zu attachen.. nach ca. 20 adressen ist die balance noch immer bei 0.
Dazu muss ich sagen, dass ich vor dem snapshot nur max. 2 Adressen generiert habe... kann also nicht sein das ich jetzt 50 adressen generieren müsste um meine balnce wieder zu haben...?!
Ich weis jetzt echt nicht mehr weiter und wäre froh wenn ihr mir weiterhelfen könntet.

Vielen Dank

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>G955FXXU1AQH3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G955FXXU1AQH3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2lte</td></tr>
<tr><td>Device model</td><td>SM-G955F</td></tr>
<tr><td>Device product name</td><td>dream2ltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
