### ISSUE TITLE
Network error 

### ISSUE THREAD

**Issue by gnewlun** [iotaledger/android-wallet-app#83]
Description:
---

I have some MI coming in but they won't because it comes up Network error. I made sure all permissions were allowed. Please help me. Thank you 

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>G955USQU1AQGL</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G955USQU1AQGL</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dream2qltesq</td></tr>
<tr><td>Device model</td><td>SM-G955U</td></tr>
<tr><td>Device product name</td><td>dream2qltesq</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
The node is already online. If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
