### ISSUE TITLE
My iotas are gone again

### ISSUE THREAD

**Issue by alinemadal** [iotaledger/android-wallet-app#85]
Description:
---

My iotas are gone again. Please i need it back. This is the second time that this happened. Please, i need you guys to fix it. And give my fourty iotas back!

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>J510MNVJU2AQG4</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MMB29M.J510MNVJU2AQG4</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>j5xnlte</td></tr>
<tr><td>Device model</td><td>SM-J510MN</td></tr>
<tr><td>Device product name</td><td>j5xnlteub</td></tr>
<tr><td>Device hardware name</td><td>qcom</td></tr>
<tr><td>ABIs</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[]</td></tr>
</table>

**Comment by pinpong** [comment]
If you have still 0 balance please check the forum post:
https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v252
