### ISSUE TITLE
Crash on open App

### ISSUE THREAD

**Issue by DammersH** [iotaledger/android-wallet-app#86]
Description:
---

1. Start App put in Password, do stuff
2. Wait for couple days (it has to be some time)
3. Open up again and witness a crash

Device info:
---
<table>
<tr><td>App version</td><td>0.7.3</td></tr>
<tr><td>App version code</td><td>7300</td></tr>
<tr><td>Android build version</td><td>G950FXXU1AQH3</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G950FXXU1AQH3</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>dreamlte</td></tr>
<tr><td>Device model</td><td>SM-G950F</td></tr>
<tr><td>Device product name</td><td>dreamltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos8895</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
@DammersH please provide me a logcat because i'm not able to reproduce this issue.

**Comment by DammersH** [comment]
11-07 07:37:24.866: E/AndroidRuntime(17800): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.iota.wallet/org.iota.wallet.ui.activity.MainActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@25ff7d8: Unmarshalling unknown type code 4653125 at offset 140

**Comment by brendakepler** [comment]
Lost IOT and app

**Comment by pinpong** [comment]
#98
