### ISSUE TITLE
Iota missing

### ISSUE THREAD

**Issue by whitfield24** [iotaledger/android-wallet-app#90]
Description:
---

Iota have been missing for 3 days help?

Device info:
---
<table>
<tr><td>App version</td><td>0.8</td></tr>
<tr><td>App version code</td><td>8000</td></tr>
<tr><td>Android build version</td><td>G925FXXU5EQDG</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>NRD90M.G925FXXU5EQDG</td></tr>
<tr><td>Device brand</td><td>samsung</td></tr>
<tr><td>Device manufacturer</td><td>samsung</td></tr>
<tr><td>Device name</td><td>zerolte</td></tr>
<tr><td>Device model</td><td>SM-G925F</td></tr>
<tr><td>Device product name</td><td>zeroltexx</td></tr>
<tr><td>Device hardware name</td><td>samsungexynos7420</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by whitfield24** [comment]
Ps I have tried 115 addresses

**Comment by pinpong** [comment]
@whitfield24 please read the [instructions](https://forum.helloiota.com/588/Help-My-IOTA-balance-is-zero-steps-to-help-you-find-your-balance-v253).

**Comment by whitfield24** [comment]
The thing is I have 297 coins it says from the site I sent it from that it has reached the iota tangle system however I never got anything in my transfers in my wallet. I have changed my address 400- 500 times, and it still says 0, are they safe?
