### ISSUE TITLE
Transaction is pending for more than a day

### ISSUE THREAD

**Issue by suhailj** [iotaledger/android-wallet-app#94]
Description:
---

My transaction is pending for more than a day. I've replayed bundle thrice and it's still pending

Device info:
---
<table>
<tr><td>App version</td><td>0.8</td></tr>
<tr><td>App version code</td><td>8000</td></tr>
<tr><td>Android build version</td><td>C675B340</td></tr>
<tr><td>Android release version</td><td>7.0</td></tr>
<tr><td>Android SDK version</td><td>24</td></tr>
<tr><td>Android build ID</td><td>BLN-L22C675B340</td></tr>
<tr><td>Device brand</td><td>HONOR</td></tr>
<tr><td>Device manufacturer</td><td>HUAWEI</td></tr>
<tr><td>Device name</td><td>HWBLN-H</td></tr>
<tr><td>Device model</td><td>BLN-L22</td></tr>
<tr><td>Device product name</td><td>BLN-L22</td></tr>
<tr><td>Device hardware name</td><td>hi6250</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by pinpong** [comment]
This is not an app issue. Try to replay the bundle again.
